name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: npm test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm run test
